### ISSUE TITLE
"Exception calling 'Substring' with '2' argument(s): 'Length cannot be less than zero.'"

### ISSUE THREAD

**Issue by arendashn-ccm** [tompatta/PowerShell#2]
When attempting to run the FSLogix clean up script, i get the following error 
```
"Exception calling "Substring" with "2" argument(s): "Length cannot be less than zero.
Parameter name: length"
At C:\CCM\script.ps1:169 char:9
+         $UserName = $ContainerDir.Name.Substring(0, $ContainerDir.Nam ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException
 
Get-ADUser : Cannot validate argument on parameter 'Identity'. The argument is null. Provide a valid value for the argument, and then try running the command again.
At C:\CCM\script.ps1:174 char:40
+         $ADUser = Get-ADUser -Identity $UserName -Properties sAMAccou ...
+                                        ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-ADUser], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.ActiveDirectory.Management.Commands.GetADUser
 "
```

Any insight on how I can resolve this error would be greatly appreciated. Thanks!

**Comment by tompatta** [comment]
@arendashn-ccm Hi! This usually happens when you have **not** set the FlipFlop option in FSLogix. Can you try running the script with the `-NoFlipFlop` option?

If this also does not work, perhaps you have non-FSLogix profile folders in the same directory. If so, you can exclude these using the `-ExcludeFolders` option.

**Comment by arendashn-ccm** [comment]
Hi! The -NoFlipFlop option resolved the issue for me and worked perfectly in my environment. Thanks!!

**Comment by tompatta** [comment]
Glad to hear it is working for you! Let me know if you have any other questions and/or suggestions! :-)
